In [7]:
import numpy as np

In [9]:
arr1 = np.array([[1,2,3,4], [8,9,10,11]]) #make 2 rows of arrays

In [10]:
arr1 # see the array

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [11]:
arr1 * arr1 # multiply arrays

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [12]:
arr1 + np.ones([2, 4])

array([[ 2.,  3.,  4.,  5.],
       [ 9., 10., 11., 12.]])

In [13]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [14]:
arr1 ** 3 # exponential arrays ^

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [15]:
4 / arr1 # divide each array cells by 4

array([[4.        , 2.        , 1.33333333, 1.        ],
       [0.5       , 0.44444444, 0.4       , 0.36363636]])

In [16]:
10 / arr1

array([[10.        ,  5.        ,  3.33333333,  2.5       ],
       [ 1.25      ,  1.11111111,  1.        ,  0.90909091]])