In [19]:
import numpy as np

In [20]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [21]:
np.save('MyArray',arr) #call the saved method to save the array, and name the title of the saved array.

In [22]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.load('MyArray.npy')

array([0, 1, 2, 3, 4])

In [24]:
arr1 = np.load('MyArray.npy') #load the saved array

In [25]:
arr1

array([0, 1, 2, 3, 4])

In [26]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.savez('ziparray.npz', x=arr1, y=arr2) #save the array in a zipped file

In [28]:
archive_array = np.load('ziparray.npz') #loads the saved zipped file

In [29]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [30]:
archive_array['y'] #loads the saved array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.savetxt('TextArray.txt', arr, delimiter=',') #save the array in a text. delimiter means space it out at a certain mark.

In [33]:
arr = np.loadtxt('TextArray.txt', delimiter=',') #load text array
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])