In [1]:
import numpy as np # import numpy to program

In [2]:
my_List = [1,2,3,4]

In [3]:
my_array = np.array(my_List) # adding the list to the array

In [4]:
my_array # printing array information

array([1, 2, 3, 4])

In [5]:
my_List2 = [5,6,7,8]

In [9]:
Sum_List = [my_List + my_List2] #adding 2 arrays together

In [7]:
my_array2 = np.array(Sum_List)

In [12]:
my_array2

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [13]:
List_2D = [my_List, my_List2] # Adding 2 lists (rows) to the array.

In [14]:
my_array3 = np.array(List_2D)

In [15]:
my_array3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
my_array3.shape # get the length of the array (rows, columns)

(2, 4)

In [18]:
np.zeros(3) # make all array cells 0

array([0., 0., 0.])

In [19]:
zero_array = np.zeros(3)

In [20]:
zero_array.dtype # get the data type of the array

dtype('float64')

In [23]:
np.ones([3, 3]) # create an array and make all of its cells = 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.empty(6) # clear the array and list how many cells you wanna create

array([0., 0., 0., 0., 0., 0.])

In [26]:
np.eye(7) # creates a diagonal array of 0 & 1 and creates the square size.

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [29]:
np.arange(6, 36, 3) # arrange the array at one point to the goal point, and the number of steps to skip

# X = Start point, Y = Goal Point, Z = Indexs to skip

array([ 6,  9, 12, 15, 18, 21, 24, 27, 30, 33])