In [1]:
import numpy as np

In [3]:
arr = np.arange(10) # create number array cells

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[7]

7

In [6]:
arr[1:4] # check to see a range of numbers

array([1, 2, 3])

In [7]:
arr[6:9] = 69 # make the array of range = 69

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5, 69, 69, 69,  9])

In [9]:
arr[2:4] = 420

In [10]:
arr

array([  0,   1, 420, 420,   4,   5,  69,  69,  69,   9])

In [11]:
arr = np.arange(0, 10) # rearange the array cells to it's ordered number

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
half_of_array = arr[0:5] # slice the array
half_of_array

array([0, 1, 2, 3, 4])

In [15]:
half_of_array[:] = 7 # Change cell number stored
half_of_array

array([7, 7, 7, 7, 7])

In [16]:
arr

array([7, 7, 7, 7, 7, 5, 6, 7, 8, 9])

In [17]:
arr_copy = arr.copy() # make a copy of the array
arr_copy

array([7, 7, 7, 7, 7, 5, 6, 7, 8, 9])

In [18]:
arr2D = np.array(([2,4,6,8], [8, 16, 24, 36], [16, 32, 48, 64])) #Declare the 2d Arrays
arr2D

array([[ 2,  4,  6,  8],
       [ 8, 16, 24, 36],
       [16, 32, 48, 64]])

In [20]:
arr2D[1] # returns 1 row

array([ 8, 16, 24, 36])

In [21]:
arr2D[1][3] # gets 1 cell

36

In [30]:
arr2D[:2,1:] #Slicing Array cells

array([[ 4,  6,  8],
       [16, 24, 36]])

In [31]:
arr2D = np.zeros((5,5))

In [32]:
arr2D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
arr_length = arr2D.shape[1] # Length of the array
arr_length

5

In [36]:
for i in range(arr_length): #make all array cells = 1
    arr2D[i]=1

arr2D

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
for i in range(arr_length): #make all array cells = i
    arr2D[i]=i

arr2D

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [38]:
arr2D[[1,3]] # call the  rows number to check the number

array([[1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.]])