In [1]:
import numpy as np

In [2]:
arr = np.arange(11) # arange 11 cells in an array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr) # squareroot the array cells

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr) # exponential array the 'e' in advanced functions

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
randArr = np.random.randn(10) #

randArr

array([ 0.26187367, -0.2929416 ,  1.42083691, -0.39772051, -1.09866518,
        0.05156543, -1.37295521,  0.79514365, -0.02785164, -0.15219193])

In [6]:
B = np.random.randn(10) 
B

array([ 1.88034579,  0.02104741, -0.96316449, -0.63003084,  0.36714948,
        0.64739155, -0.23851661, -0.91587032,  1.83532275, -1.03914332])

In [7]:
np.add(randArr,B) # binary function

array([ 2.14221946, -0.27189418,  0.45767241, -1.02775135, -0.7315157 ,
        0.69895698, -1.61147182, -0.12072667,  1.80747111, -1.19133525])

In [8]:
np.maximum(randArr,B) # finds the maximum of 2 array values

array([ 1.88034579,  0.02104741,  1.42083691, -0.39772051,  0.36714948,
        0.64739155, -0.23851661,  0.79514365,  1.83532275, -0.15219193])

In [9]:
website = 'https://numpy.org/doc/stable/user/index.html' # Open Websites
import webbrowser
webbrowser.open(website)

True