In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape(3, 3)
arr1 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis=1) #display horizontally

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis=0) #display vertically

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0, 1, 2], index=['A', 'B', 'C'])

ser2 = Series([3, 4], index=['D', 'E'])

In [8]:
ser1

A    0
B    1
C    2
dtype: int64

In [9]:
ser2

D    3
E    4
dtype: int64

In [10]:
pd.concat([ser1, ser2])

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [11]:
pd.concat([ser1, ser2], axis=0) # mainly focus is to displays the rows

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [12]:
pd.concat([ser1, ser2], axis=1) # mainly focus is to displays the columns, so the 2 series will be in different columns.

0    1
A  0.0  NaN
B  1.0  NaN
C  2.0  NaN
D  NaN  3.0
E  NaN  4.0

In [13]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2']) #set key index as cat1 and cat2 for the 2 series

cat1  A    0
      B    1
      C    2
cat2  D    3
      E    4
dtype: int64

In [15]:
df1 = DataFrame(np.random.randn(4, 3), columns=['X', 'Y', 'Z'])

df2 = DataFrame(np.random.randn(3, 3), columns=['X', 'Q', 'Y'])

In [16]:
df1

X         Y         Z
0 -0.794282 -0.594830  0.015820
1  1.499065  1.296571 -1.050698
2 -0.233076  0.463188 -1.833385
3  0.283437 -0.215553 -0.958085

In [17]:
df2

X         Q         Y
0 -0.278502 -0.444857 -0.131308
1  0.523663 -0.128166  0.186320
2  1.093455  0.160178  0.718610

In [18]:
pd.concat([df1, df2]) # concatenate the 2 DataFrames, mainly displays the rows

X         Y         Z         Q
0 -0.794282 -0.594830  0.015820       NaN
1  1.499065  1.296571 -1.050698       NaN
2 -0.233076  0.463188 -1.833385       NaN
3  0.283437 -0.215553 -0.958085       NaN
0 -0.278502 -0.131308       NaN -0.444857
1  0.523663  0.186320       NaN -0.128166
2  1.093455  0.718610       NaN  0.160178

In [20]:
pd.concat([df1, df2], axis=1) # concatenated Data frame that displays the columns of 2 separate dataframes.

X         Y         Z         X         Q         Y
0 -0.794282 -0.594830  0.015820 -0.278502 -0.444857 -0.131308
1  1.499065  1.296571 -1.050698  0.523663 -0.128166  0.186320
2 -0.233076  0.463188 -1.833385  1.093455  0.160178  0.718610
3  0.283437 -0.215553 -0.958085       NaN       NaN       NaN

In [22]:
pd.concat([df1, df2], ignore_index=True) # renames the 2 indexes for the concatenated data frame.

X         Y         Z         Q
0 -0.794282 -0.594830  0.015820       NaN
1  1.499065  1.296571 -1.050698       NaN
2 -0.233076  0.463188 -1.833385       NaN
3  0.283437 -0.215553 -0.958085       NaN
4 -0.278502 -0.131308       NaN -0.444857
5  0.523663  0.186320       NaN -0.128166
6  1.093455  0.718610       NaN  0.160178

In [23]:
pd.concat([df1, df2], ignore_index=True, axis=1) #rearanges by columns. fits whatever order.

0         1         2         3         4         5
0 -0.794282 -0.594830  0.015820 -0.278502 -0.444857 -0.131308
1  1.499065  1.296571 -1.050698  0.523663 -0.128166  0.186320
2 -0.233076  0.463188 -1.833385  1.093455  0.160178  0.718610
3  0.283437 -0.215553 -0.958085       NaN       NaN       NaN