In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
df = DataFrame(np.arange(16).reshape(4, 4))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [3]:
blender = np.random.permutation(4)
blender #permutates the array

array([2, 3, 0, 1])

In [4]:
df.take(blender) #permutates the row in the order of blender array

0   1   2   3
2   8   9  10  11
3  12  13  14  15
0   0   1   2   3
1   4   5   6   7

In [5]:
box = np.array([1, 2, 3])
box # box with 3 marbles

array([1, 2, 3])

In [8]:
shaker = np.random.randint(0, len(box), size=12) #randint(start, end, size of array)

In [9]:
shaker # randomize the numbers from 0-2 for each array.

array([1, 0, 1, 2, 2, 2, 0, 0, 0, 2, 0, 2])

In [10]:
hand_grabs = box.take(shaker)
# grabs 3 marbles. and apply the result of hand_grabs to determine the chosen number on each turns.
hand_grabs

array([2, 1, 2, 3, 3, 3, 1, 1, 1, 3, 1, 3])